### ISSUE TITLE
Forking and branching

### ISSUE THREAD

**Issue by nmtarr** [usgs-bcb/bcb-dm#10]
This will be my first time using github in this way.  Can someone clarify how I would contribute to the repository if I had code or comments to add?  Would I fork the bcb-dm repository, clone it to my computer, create a new branch that I edit, and then make a pull request to incorporate that new code?  Or is there a more direct way to do all that.

Nathan

**Comment by albenson-usgs** [comment]
My understanding is that you clone and then create a pull request. But maybe @skybristol or @aulenbac have more input.

**Comment by aulenbac** [comment]
As @albenson-usgs points out, it is a remarkably flexible and rich system to work in. Personally, I am continually learning new tricks and occasionally simpler ways of doing things. As a member of the repo team, you can make comments. You can also make code contributions in the manner you said: forking the bcd-dm repository to your online nmtarr GitHub account, cloning that down to your local machine via https or ssh, doing your coding there (branches! hooray!), and when you are ready, pushing your work back up to nmtarr and issuing a pull request to bcb-dm. We are reviewing and merging pull requests fairly quickly. Does that answer your questions? If not, let me know offline and we can work together. git is a neat, fun tool and there is a lot to know. I often find myself hitting GitHub's help pages (https://help.github.com/). Atlassian writes some nice stuff, too. I refer to this post (https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests) for pull request advice.

**Comment by nmtarr** [comment]
Sounds good.  That's exactly what I wanted to know.  Thanks Steve!
