### ISSUE TITLE
Ideas for Topics of Focus During the Protected Areas Workshop (start of a general agenda)

### ISSUE THREAD

**Issue by jpmagee** [usgs-bcb/bcb-dm#16]
Hello workshop participants:

Below are some ideas for topics of discussion (general agenda) during our meeting this week.  I realize we can't tackle too many things but wanted to make sure the ideas at the end of this list were noted as things we would like to discuss at some point. Thanks.

I. Introductions & Meeting Purpose

II. What it takes to do a PAD-US Update: Mason (see details to be posted to GitHub by Mason)

- Cover topics such as: 1) what Mason is doing to manage source data; 2) what are the range of problems Mason is dealing with - different sources - different challenges?  

III. Establishing a collection of PAD-US source material in ScienceBase:

- Purpose  and  Intent (public or private?)(Sky)
- Data sharing considerations and concerns from our data stewards. How to address those concerns. (Lisa, Mason, Julie and the group).
- Discussion followed by working session (TBD – time and who will participate).

IV. Other topics of interest for potential consideration to work on:

- Persistent Identifiers

- Revising and refining PAD-US reconciliation and QA/QC scripts

**Comment by dwief-usgs** [comment]
I'll add one bullet under topic 3.

Python demonstration of how we could potentially use the BIS and GC2 to store, document, visualize and analyze PAD-US information.  https://github.com/usgs-bcb/bcb-dm/blob/master/NationalParksBIS.ipynb  (This notebook is under review in an outstanding pull request and will likely being changing over the next day, but the first few stages of the example will be outlined when the pull request is accepted.)

**Comment by skybristol** [comment]
I think some aspects of the proposed topics make sense. I'd like to suggest the following modifications:

1. Introductions and expectations (clear the air up front on what folks are expecting to get out of/contribute to this meeting)
2. Purpose, vision, and USGS mission comments (I have some thoughts to share)
3. Working group format (Steve or Sky; expectations and methods for capturing proceedings via GitHub)
4. Current PAD-US data assembly process - focus on pain points (Mason lead, Lisa chime in, frequent breaks for questions and brainstorming)
5. How does current process jive with data management plan? (Look at Protected Areas notebook, which now starts to dovetail with PAD-US DMP)
6. Working steps toward addressing pain points (Mason's and other considerations from no. 4 discussion)
6.a. (Possibly) Cataloging, documenting, repositing source data
6.b. (Possibly) Code-driven data integration methods (Daniel's work, others)
6.c. (Possibly) New model for data system vs. database, including persistence and temporality
6.d. (Possibly) How does all of this impact messaging/positioning/communicating PAD-US mission?
