### ISSUE TITLE
Get the spreadsheet of PAD-US source data available in some form for folks to work with

### ISSUE THREAD

**Issue by skybristol** [usgs-bcb/bcb-dm#4]
I've seen a spreadsheet (Google Sheet, I think) in the past with more detailed information on PAD-US sources. One idea is to use this as the starting point with some code to generate ScienceBase Items that we can use as the formal reference point for PAD-US source data. That will give us a persistent identifier with some level of depth behind it for recording the who, when, what, and how of source data.

It would be great to get a copy of that spreadsheet somewhere that we can take a look at to start better understanding where the data come from and what all information we have recorded in our backend data management process.

**Comment by MasoncBSU** [comment]
Here is a [link to the Google Sheet](https://docs.google.com/spreadsheets/d/17TNKxCuzPRwTEax5bood_ez68FlrSC35P3MgNVF2R7I/edit?usp=sharing) that is being used to track source data information for the PAD-US 2.0 update.

**Comment by skybristol** [comment]
Sweet! Thank you so much, @MasoncBSU.
